{
    response: [
    {
    _id: "64a4bc189cbfca6999df06d3",
    name: "Cairo",
    country: "Egypt",
    description: "Discover the mysterious Pyramids of Egypt in Cairo and let yourself be fascinated by their ancient grandeur. Immerse yourself in ancient history as you marvel at these magnificent structures built by the pharaohs. Admire the imposing Pyramid of Khufu, the enigmatic Sphinx, and the Giza complex, a UNESCO World Heritage site. Explore the inner chambers and uncover the secrets held within these architectural wonders. Experience a unique journey and connect with the greatness of Egyptian civilization at the Pyramids of Cairo!",
    continent: "Africa",
    topAttractions: "Great Pyramid of Giza",
    image: "https://firebasestorage.googleapis.com/v0/b/mytinerary-unhcr.appspot.com/o/Esfinge%20El%20cairo%20Egipto.jpg?alt=media&token=0a69d6e3-27e4-4bc4-8576-d923513b28af",
    __v: 0,
    avatarCountry: "https://static.vecteezy.com/system/resources/previews/018/880/403/large_2x/3d-flag-of-egypt-on-avatar-circle-png.png"
    },
    {
    _id: "64a4bc189cbfca6999df06d6",
    name: "New York",
    country: "EE.UU",
    description: "Discover the majestic Statue of Liberty in New York! This iconic symbol of liberty and democracy will captivate you with its imposing presence and inspiring history. Climb up to the crown of the statue to enjoy breathtaking views of the city of skyscrapers and the Manhattan skyline. Immerse yourself in the historical legacy of this monument and let yourself be carried away by the excitement of being close to a globally recognized icon. Come and feel the freedom emanating from the Statue of Liberty in an unforgettable experience in the Big Apple!",
    continent: "America",
    topAttractions: "Statue of Liberty",
    image: "https://firebasestorage.googleapis.com/v0/b/mytinerary-unhcr.appspot.com/o/Estatua%20de%20la%20libertad%20-%20NY%20USA.jpg?alt=media&token=6d1cbac7-3844-4e0e-9dbb-35f7a661d7f6",
    __v: 0,
    avatarCountry: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Flag_of_the_United_States.svg.webp?alt=media&token=8c831592-ddbe-4529-b002-236722d76261"
    },
    {
    _id: "64a4bc189cbfca6999df06d9",
    name: "Paris",
    country: "France",
    description: "Discover the iconic Eiffel Tower and immerse yourself in the magic of Paris! This majestic wrought-iron structure, an undisputed symbol of the City of Light, awaits you with its breathtaking panoramic views and captivating history. Climb to the top of the Eiffel Tower and marvel at the spectacular views of Parisian rooftops, elegant boulevards, and iconic landmarks that adorn the skyline. Immerse yourself in the elegance and romance that envelop this architectural icon as you uncover the secrets of its construction and its role in France's history. Don't miss the opportunity to have an unforgettable experience and capture the most impressive memories from the top of the Eiffel Tower. Come and be swept away by the beauty and charm of this iconic monument in Paris!",
    continent: "Europe",
    topAttractions: "Eiffel Tower",
    image: "https://firebasestorage.googleapis.com/v0/b/mytinerary-unhcr.appspot.com/o/Torre%20Eiffel-Paris%20Francia.jpg?alt=media&token=b920d8ce-458e-40a3-869c-ac6da9312b6a",
    __v: 0,
    avatarCountry: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/FRANCIA%20FLAG.png?alt=media&token=dcc9791f-c144-4284-bf35-14a8669b3bb4"
    },
    {
    _id: "64a4bc189cbfca6999df06df",
    name: "San Carlos de Bariloche",
    country: "Argentina",
    description: "Located at the base of the Andes, San Carlos de Bariloche is a world-renowned destination for skiing. This place is immersed in a breathtaking landscape that offers all the natural wonders of Argentina. Visitors can delight in the snow, serene lakes, and tranquil beaches while enjoying vibrant nightclubs and exquisite gourmet cuisine. Throughout the year, the area hosts numerous music festivals, art exhibitions, and conventions.",
    continent: "America",
    topAttractions: "Cerro campanario",
    image: "https://firebasestorage.googleapis.com/v0/b/mytinerary-unhcr.appspot.com/o/Bariloche%20-%20Rio%20negro%20Argentina.jpg?alt=media&token=ff6f3de6-3fd6-4d2e-bae2-ebf15d740d28",
    __v: 0,
    avatarCountry: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Flag_of_Argentina.svg.webp?alt=media&token=2096e365-45f8-42bc-ac43-828fc51de73a"
    },
    {
    _id: "64a4bc199cbfca6999df06e2",
    name: "Pekin",
    country: "China",
    description: "Welcome to a capital city with a history that dates back around 3000 years. You will find that history abounds in Beijing, both ancient and more recent. To experience the most authentic market, don't miss Panjiayuan Market instead of the touristy Silk Market. A visit to the Great Wall, the longest man-made structure in the world, is absolutely essential.",
    continent: "Asia",
    topAttractions: "Bell Tower, Forbidden City, Badaling",
    image: "https://firebasestorage.googleapis.com/v0/b/viajerisimo-arg.appspot.com/o/mytinerary%2FMURALLA-WEB.jpg?alt=media&token=d74f37e8-8109-4a9c-bb3e-2404a63c8136&_gl=1*1ka1nxe*_ga*MjE0Mzg4Mjg5NC4xNjg1NDA5ODEx*_ga_CW55HF8NVT*MTY4NjUxNTU2Mi4xNi4xLjE2ODY1MTY5OTguMC4wLjA.",
    __v: 0,
    avatarCountry: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Flag_of_the_People's_Republic_of_China.svg.png?alt=media&token=7b37c36e-ed9b-4131-b375-8f7f520d21b0"
    },
    {
    _id: "64a4bc199cbfca6999df06e5",
    name: "Santorini",
    country: "Greece",
    description: "Even if you've never been to these Cycladic islands in the Aegean Sea, you would immediately recognize them by their colorful houses carved into the cliffs, their sapphire-colored waters, and their chalk-white buildings with cobalt-blue domes. Wander along the tranquil black sand beaches or stroll through the streets of a provincial village like Imerovigli. The beautiful Oia is world-famous for its sunsets, which seem to pass through a kaleidoscope of colors before fading away and transforming into starlight.",
    continent: "Europe",
    topAttractions: "The Castle of St Nicholas, Amoudi Bay",
    image: "https://firebasestorage.googleapis.com/v0/b/viajerisimo-arg.appspot.com/o/mytinerary%2FSantorini_HDR_sunset.jpg?alt=media&token=b79fc317-8f0b-44ca-bbb5-bb4d6dca800b&_gl=1*1mb6gl3*_ga*MjE0Mzg4Mjg5NC4xNjg1NDA5ODEx*_ga_CW55HF8NVT*MTY4NjUzMjExMC4xOC4xLjE2ODY1MzI2NzguMC4wLjA.",
    __v: 0,
    avatarCountry: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Flag_of_Greece.svg.png?alt=media&token=07366d96-d071-4085-ad69-b2cc68bcf383"
    },
    {
    _id: "64a4bc199cbfca6999df06e8",
    name: "Queensland",
    country: "Australia",
    description: "Some of Queensland's most remarkable sights require you to leave terra firma. Off its coast sits the Great Barrier Reef, the world's largest coral reef. Snorkel and scuba among 1500 resident fish species, or sail through the Whitsundays’ white-sand atolls. Back on dry land, you’ll find tropical escapes in the Daintree Rainforest to the north, rugged outback to the west and alfresco dining on the Gold Coast in the south. South East Queensland boasts mountain views, vineyards and Brisbane.",
    continent: "Oceania",
    topAttractions: "Noosa National Park, Lone Pine Koala Sanctuary, Heart Reef",
    image: "https://firebasestorage.googleapis.com/v0/b/viajerisimo-arg.appspot.com/o/mytinerary%2FbarreraCoral.jpg?alt=media&token=5d30841b-15e7-4f6a-884f-fd333a207eb0&_gl=1*dti7bu*_ga*MjE0Mzg4Mjg5NC4xNjg1NDA5ODEx*_ga_CW55HF8NVT*MTY4NjUzMjExMC4xOC4xLjE2ODY1MzMxOTEuMC4wLjA.",
    __v: 0,
    avatarCountry: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Flag_of_Australia.svg.png?alt=media&token=fc96b407-44f4-4625-b06a-176232541c74"
    },
    {
    _id: "64a4bc199cbfca6999df06eb",
    name: "Iguazu Port",
    country: "Argentina",
    description: "Perched at the Triple Frontier, where Brazil, Paraguay and Argentina meet, Puerto Iguazu is linked to Brazil by the Tancredo Neves bridge. It is home to the Museum of Images of the Jungle, the Mborore Museum, a bird rehabilitation center and the famed Iguazu National Park. The National Park is home to 275 waterfalls, including the world-renowned Iguazu Falls, which plunges 270 feet. A subtropical climate means it's warm in winter and hot in summer, with temperatures soaring up to 40°C.",
    continent: "America",
    topAttractions: "Devil's Throat, San Martin Island",
    image: "https://firebasestorage.googleapis.com/v0/b/viajerisimo-arg.appspot.com/o/mytinerary%2Fcataratas.jpg?alt=media&token=7c580b31-463f-4a86-b16d-e3fcfb6584a2&_gl=1*bag8pu*_ga*MjE0Mzg4Mjg5NC4xNjg1NDA5ODEx*_ga_CW55HF8NVT*MTY4NjYxNTM5My4yMC4xLjE2ODY2MTU0NTkuMC4wLjA.",
    __v: 0,
    avatarCountry: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Flag_of_Argentina.svg.webp?alt=media&token=2096e365-45f8-42bc-ac43-828fc51de73a"
    },
    {
    _id: "64a4bc199cbfca6999df06f1",
    name: "Florence",
    country: "Italy",
    description: "There's no better place for Renaissance art and architecture than Florence—from the Galleria dell'Accademia (home to Michelangelo's David) to the cathedrals and arches that make up the Piazzale Michelangelo. But just beyond the main sights, you'll find some of the city's off-the-beaten-path gems, with (bonus) way less crowds. San Miniato al Monte is worth the climb for the frescoes and unbeatable views. Oltrarno, just across the river, offers plenty of vintage shops, boutiques, and cool cafes. When in doubt, do as the locals do: Post up in a piazza with a plate of fresh tagliatelle and a glass of Chianti and watch the city go by.",
    continent: "Europe",
    topAttractions: "Piazza del Duomo, Museo Galileo, David & Accademia Gallery",
    image: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Florencia.jpg?alt=media&token=fdd3d2c6-21f1-4e24-a0fc-762ee51db0b3",
    __v: 0,
    avatarCountry: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Flag_of_Italy.svg.png?alt=media&token=2e360ded-0966-4876-900e-26eb668315e1"
    },
    {
    _id: "64a4bc199cbfca6999df06f7",
    name: "Osaka",
    country: "Japan",
    description: "Home to nearly nine million and powering an economy that exceeds both Hong Kong's and Thailand's, Osaka packs quite a punch. The confident, stylish city is a shopping hub, with fabulous restaurants and nightlife. It's an ideal base for exploring the Kansai region; Kyoto's World Heritage Sites, Nara's temple, and Koya-san's eerie graves are within 90 minutes by train. Top city attractions include the aquarium, Osaka Castle, Universal Studios Japan, and the futuristic Floating Garden Observatory.",
    continent: "Asia",
    topAttractions: "Osaka Castle, Dotombori District, Universal Studios Japan",
    image: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Osaka.jpg?alt=media&token=59827b45-5f99-4b66-bcb7-704741121dd3",
    __v: 0,
    avatarCountry: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Flag_of_Japan.svg.png?alt=media&token=72cea25c-0659-40bb-b7a6-825a572e25c6"
    },
    {
    _id: "64a4bc1a9cbfca6999df06fa",
    name: "Bangkok",
    country: "Thailand",
    description: "There are cities and then there is Bangkok. Temples like Wat Pho are thronged with devotees all day. Street food sizzles all evening. The heat never stops. And the nightlife—from sleazy Patpong to ritzy rooftop bars—is second to none. But the pleasures don't end there. Night markets, mega malls, and the massive Chatuchak Weekend Market all make Bangkok a shoppers’ (and souvenir-hunter’s) dream. You’ll need to prepare yourself—Bangkok is intense. But for travellers craving local secrets and 24/7 energy, there's nowhere in the world quite like it.",
    continent: "Asia",
    topAttractions: "Temple of the Emerald Buddha, Wat Phra Chetuphon, Chatuchak Weekend Market",
    image: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Bangkok.jpg?alt=media&token=966e9787-a10e-4be9-b734-6742746a5803",
    __v: 0,
    avatarCountry: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Flag_of_Thailand.svg.png?alt=media&token=ec50d2d2-dfe6-4bd8-b347-614aecb0b3c3"
    },
    {
    _id: "64a4bc1a9cbfca6999df06fd",
    name: "Dubrovnik",
    country: "Croatia",
    description: "Medieval meets Mediterranean in Dubrovnik, where towering stone fortresses rise from the glistening Adriatic Sea. Walk along the ancient walls that surround Old Town to get a sweeping view of the city—dotted with Romanesque-Gothic monasteries, palaces, and plenty of terracotta rooftops, it’s the stuff of Game of Thrones dreams (it was filmed here, after all). There’s no shortage of beaches, most of them pebbly and low-key, but if you're looking for a more clubby vibe, hit Copacabana Beach where you can spend the day jet skiing, sipping cocktails, or lounging on a sunbed.",
    continent: "Europe",
    topAttractions: "Walls of Dubrovnik, Adriatic Sea, Blue Cave Small",
    image: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Dubronik.jpg?alt=media&token=a84cc1ea-14b9-48bc-8b1c-2bb61cbf867f",
    __v: 0,
    avatarCountry: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Flag_of_Croatia.svg.png?alt=media&token=6ecf4f10-f2cf-4a99-a13d-42425641f91e"
    },
    {
    _id: "64a4bc1a9cbfca6999df0700",
    name: "Prague",
    country: "Czech Republic",
    description: "The bohemian allure and fairytale features of Prague make it a perfect destination for culture vultures who want to immerse themselves in history, art, music, and architecture. You could devote an entire day to exploring Prazsky hrad (Prague Castle), then refuel over a hearty dinner at a classic Czech tavern. Spend some time wandering Old Town Square before heading over to the Astronomical Clock as it performs a mechinical promenade on the hour. Prague's best bars are often historic pubs where you can spend the better part of a night tipping back central Europe's top-shelf beers.",
    continent: "Europe",
    topAttractions: "Charles Bridge, Prague Castle, Old Town Hall with Astronomical Clock",
    image: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Praga.webp?alt=media&token=788fc385-4544-4e2a-9776-1ca332418e78",
    __v: 0,
    avatarCountry: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Flag_of_the_Czech_Republic.svg.png?alt=media&token=e8492865-2401-4383-b3d4-89b6949c6d55"
    },
    {
    _id: "64a4bc1a9cbfca6999df0706",
    name: "Las Vegas",
    country: "EE.UU",
    description: "Whatever you can dream up, Las Vegas delivers: Michelin-starred restaurants, 24-hour wedding chapels, larger-than-life scenery, slot machines, all of it. But just when you think you have Vegas pinned down, it surprises you. Consider Meow Wolf, an immersive experience that's equal parts theme park and art gallery. Or the ice rink at the Cosmopolitan (winter in the desert!). Head out past the Strip, and you'll find state parks and scenery for days in spots like Valley of Fire and Red Rocks Canyon. It's gems like these that round out Vegas as a destination for families and non-partiers, too.",
    continent: "America",
    topAttractions: "Fountains of Bellagio, Red Rock Canyon, The Strip",
    image: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Las%20vegas.jpg?alt=media&token=71c41fef-6b0c-4e74-a8de-e86f49677724",
    __v: 0,
    avatarCountry: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Flag_of_the_United_States.svg.webp?alt=media&token=8c831592-ddbe-4529-b002-236722d76261"
    },
    {
    _id: "64a4bc1a9cbfca6999df0709",
    name: "Marrakech",
    country: "Morocco",
    description: "Colorful souks, Moorish architecture, intimate gardens and boutique hotels--Marrakesh is unforgettable. Spend your days exploring the quiet courtyards and snaking alleyways of the historic Medina, walking through the serene Jardin Majorelle or taking in the beauty of the city's mosques before ending the evening at a one-of-a-kind riad.",
    continent: "Africa",
    topAttractions: "Le Jardin Secret, Medina of Marrakech, Jemaa el-Fnaa",
    image: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/medina-of-marrakech.jpg?alt=media&token=2a7c70d0-2561-4cb5-b699-88aa3b588145",
    __v: 0,
    avatarCountry: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Flag_of_Morocco.svg.png?alt=media&token=abb568cc-7e82-4c9f-9c83-2a76d672ef4f"
    },
    {
    _id: "64a4bc1a9cbfca6999df070c",
    name: "Barcelona",
    country: "Spain",
    description: "There's nowhere in the world like Barcelona. From days spent strolling the Gothic Quarter to afternoons at the beach and nights partying ‘til dawn - the city is magnetic. You won’t be the only tourist here (especially during the summer), but even amid the crowds you’ll find your own Mediterranean magic any time of year. Explore the Jameson City Guide to discover eclectic streets, tasty tapas, and a skateboarding culture that's second to none. Enjoy Jameson Responsibly.",
    continent: "Europe",
    topAttractions: "Basílica de la Sagrada Familia, Parc de Montjuic, Casa Batlló",
    image: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Barcelna.jpg?alt=media&token=a3a1bfe6-454d-4c37-9988-6c4ccc24d10f",
    __v: 0,
    avatarCountry: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Bandera_de_Espa%C3%B1a.svg.png?alt=media&token=783875d1-6e5c-45c8-afc5-9d51ad90b012"
    },
    {
    _id: "64a4bc1a9cbfca6999df070f",
    name: "Amsterdam",
    country: "Netherlands",
    description: "From its picturesque canals and bridges to its historic homes, Amsterdam is a full-blown fairytale. The brightly-coloured bicycles and tulip stands around town don’t hurt either. Must-see sights include the Anne Frank House, the Van Gogh Museum, and the world's only floating flower market. Rent a bike and join thousands of locals peddling around. Other visitors might want to linger in the local coffee shops, which is just a normal part of the city's landscape.",
    continent: "Europe",
    topAttractions: "Anne Frank House, Rijksmuseum, Zaanse Schans",
    image: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/amsterdam.jpg?alt=media&token=cf001593-4a20-4c96-bc34-60fb7f618db0",
    __v: 0,
    avatarCountry: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Flag_of_the_Netherlands.svg.png?alt=media&token=f126ca93-1e15-4c54-be67-12808c663ca1"
    },
    {
    _id: "64a4bc1b9cbfca6999df0712",
    name: "Rio de Janeiro",
    country: "Brazil",
    description: "With its plentiful beaches, dramatic mountains, and backdrop of samba and bossa nova rhythms, it's easy to fall in love with Rio de Janeiro. Made famous in song, Ipanema Beach is still the place to stroll, sunbathe, and be seen. The largest Art Deco statue in the world, Christ the Redeemer, beckons visitors to Corcovado Mountain. And if you're coming for Carnaval, Rio's annual celebrations are bacchanalian extravaganzas of feasting, music, dance, and costumed revelry.",
    continent: "America",
    topAttractions: "Escadaria Selarón, Copacabana Beach, Corcovado - Christ the Redeemer",
    image: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Rio.webp?alt=media&token=416f6068-4d47-4d5e-9579-63e1211ba97d",
    __v: 0,
    avatarCountry: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Flag_of_Brazil.svg.png?alt=media&token=54228f5b-631b-41b3-bf46-44a5b3ff7a70"
    },
    {
    _id: "64a4bc1b9cbfca6999df0715",
    name: "Bali",
    country: "Indonesia",
    description: "No island has enchanted travellers quite like Bali. Less than half the size of Hawaii's big island, Bali manages to pack countless adventures into one small package. Dazzling beaches beckon the sun seekers and surfers along the island's southwest coast, while ancient temples and a thriving wellness scene draw travellers inland to Ubud. It's the kind of place where hedonists, relaxation-seekers, and ecotourists can all find something to enjoy, from wild nightclubs in Seminyak and Kuta to luxury clifftop hotels in Nusa Dua to the pristine jungles and volcanic landscapes of the island's north.",
    continent: "Asia",
    topAttractions: "Kelingking Beach, Tanah Lot Temple, Ulun Danu Bratan Temple",
    image: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Bali.jpg?alt=media&token=0f0c78a6-4910-433d-9b79-42a4c963c869",
    __v: 0,
    avatarCountry: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Flag_of_Indonesia.svg.png?alt=media&token=3ad91bae-1f8e-41c4-a2ce-c33c94ecf0d1"
    },
    {
    _id: "64a4c035bb590e00522f9d66",
    name: "Cuzco",
    country: "Peru",
    description: "The splendor of the Inca and Andean Baroque are side by side on the stone streets of Cusco, represented by the Temple of Coricancha and the Church of Santo Domingo, which flank the Plaza de Armas. In this high-altitude melting pot of Amerindian and mestizo cultures, you will find incredible ruins to explore like Machu Picchu, the citadel, was built in the 1450s by the Inca emperor Pachacuti. This place is considered, a masterpiece of architecture and engineering. Its unique architectural and landscape features, along with the veil of mystery that has surrounded it in much of the literature published about the site, have made it one of the most famous tourist destinations on the planet, as well as one of the seven wonders of the world.",
    continent: "America",
    topAttractions: "Templo del Sol, Intihuatana, Camino Inca",
    image: "https://firebasestorage.googleapis.com/v0/b/viajerisimo-arg.appspot.com/o/mytinerary%2FMachu_Picchu%2C_Peru.jpg?alt=media&token=affb9194-14cc-4f3c-a71d-1f624fe56573&_gl=1*3caw6j*_ga*MjE0Mzg4Mjg5NC4xNjg1NDA5ODEx*_ga_CW55HF8NVT*MTY4NjUxNTU2Mi4xNi4xLjE2ODY1MTgxNDcuMC4wLjA.",
    __v: 0,
    avatarCountry: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Flag_of_Peru_(1825%E2%80%931884).svg.png?alt=media&token=20582422-12d7-4b49-8c68-71edc8624764"
    },
    {
    _id: "64a4c77ebb590e00522f9da0",
    name: "Roma",
    country: "Italia",
    description: "Immerse yourself in the grandeur of the Roman Colosseum in Rome! This ancient amphitheater will transport you to the time of the Roman Empire, where you can relive the excitement of gladiatorial spectacles and the magnificence of Roman architecture. Explore its imposing ruins and walk through the corridors where thousands of spectators cheered on brave gladiators. Behold the magnificent arena and uncover the secrets held within each stone. Let history come to life before your eyes as you explore this icon of antiquity. You cannot miss the opportunity to visit the Colosseum and experience the impressive legacy of Rome!",
    continent: "Europe",
    topAttractions: "Roman Colosseum, Fontana di Trevi",
    image: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Roma.jpg?alt=media&token=366de8b0-081e-41fa-8649-35bd520b523a",
    __v: 0,
    avatarCountry: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Flag_of_Italy.svg.png?alt=media&token=2e360ded-0966-4876-900e-26eb668315e1"
    },
    {
    _id: "64a4c77ebb590e00522f9da6",
    name: "Agra",
    country: "India",
    description: "Discover the majestic Taj Mahal on an exclusive day trip from Delhi, without worrying about taking a train or coordinating taxis in Agra. With our pick-up service from your hotel or airport in Delhi, you will be transported in a comfortable private air-conditioned car and greeted by your personal guide at the Taj Mahal. Enjoy a private tour of this iconic UNESCO-recognized mausoleum as you listen to the fascinating love story that surrounds it before embarking on the return journey. This experience includes entrance tickets and a specialized guide.",
    continent: "Asia",
    topAttractions: "Taj Mahal",
    image: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Agra.webp?alt=media&token=92d1eb1f-1a13-4738-828e-c7c841706f06",
    __v: 0,
    avatarCountry: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Flag_of_India.svg.png?alt=media&token=12a6d022-329e-4b4b-b5b9-9d9b185d9e40"
    },
    {
    _id: "64a4c77fbb590e00522f9dae",
    name: "Kathmandu",
    country: "Nepal",
    description: "Nepal's capital is situated in a valley full of historic sites, ancient temples and shrines, golden pagodas and fascinating villages. Hotels, bars and restaurants cater to all budgets. Shops offer handicrafts, carpets and Nepali paper prints. Bus services, taxis and bicycles open up the city. Trek to see the Monkey Temple, the valley's oldest and most sacred shrine. Mingle with locals and animals amid Durbar Square's monuments and temples, or join mountain trekkers in the bustling Thamel District.",
    continent: "Asia",
    topAttractions: "Monkey Temple, Everest Base Camp",
    image: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Katmandu.jpg?alt=media&token=c059614b-03c5-4e25-a9bd-1cb62d2e6901",
    __v: 0,
    avatarCountry: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Nepal%20flag.png?alt=media&token=7f1ce026-fb4f-4680-9446-4050aa013200"
    },
    {
    _id: "64a4c77fbb590e00522f9db7",
    name: "Cancun",
    country: "Mexico",
    description: "Cancun's a pretty well-known spot for spring breakers (and spring breakers at heart)—but its fun-loving spirit, miles of resorts, and nonstop nightlife is only one small part of the story. The city is one of Mexico's all-around gems—literally made for vacationing. Its velvety beaches are some of the best the Caribbean has to offer, while scuba divers and snorkelling buffs alike will find plenty of action in the surf, including the Museo Subacuático de Arte, with its more than 500 underwater sculptures. On the outskirts of the city, sites like the pyramids of Chichen Itza give a deep-dive on the area's sacred Mayan heritage.",
    continent: "America",
    topAttractions: "Chichen Itza, Playa Langosta, Xoximilco Cancun by Xcaret",
    image: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Xcaret.jpg?alt=media&token=f24f6f71-04e0-4114-a030-d8f8f3a81425",
    __v: 0,
    avatarCountry: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Flag_of_Mexico.svg.png?alt=media&token=18c68040-c327-4359-be6b-c8e1eb0546cc"
    },
    {
    _id: "64a4dff76be1aa4b11d0584c",
    name: "Meddellin",
    country: "Colombia",
    description: "Medellin has been transformed. It’s now a vibrant destination for travelers seeking a culturally rich vacation. Medellin rises proudly from the belly of the Aburrá Valley, and its natural beauty makes a perfect setting for hiking, zip lining and horseback riding. Travel through lush jungle to Piedra de Penol, then climb the 740 steps to the top—a journey within a journey that rewards you with unforgettable views.",
    continent: "America",
    topAttractions: "Parque Arvi, Pueblito Paisa, Medellin Metrocable",
    image: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Medellin.jpg?alt=media&token=eb766637-0269-4269-b32a-1097f20160d5",
    __v: 0,
    avatarCountry: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Flag_of_Colombia.svg.webp?alt=media&token=d9cedfde-2852-4a63-9b38-8a4a773a5184"
    },
    {
    _id: "64a4e6356be1aa4b11d05871",
    name: "Tromso",
    country: "Norway",
    description: "Tucked above the Arctic Circle, Tromso puts on a wintertime display of northern lights swirling across the sky. Come summer, darkness disappears as the city glows with the midnight sun. But whatever the season, you'll be spellbound by the city's cute fishing villages, gushing waterfalls, and narrow fjords. Music is a major part of the Tromso culture, so join the locals at a concert in the Arctic Cathedral or dance to techno and electronica at the annual Insomnia Festival.",
    continent: "Europe",
    topAttractions: "Northern Lights, Tromso Fjords",
    image: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Noruega.jpg?alt=media&token=0d46b746-8d52-4289-afa7-d0a4b96abc8c",
    __v: 0,
    avatarCountry: "https://firebasestorage.googleapis.com/v0/b/tree-store.appspot.com/o/Flag_of_Norway.svg.png?alt=media&token=a88858cc-7c49-4c98-b50d-b9add3ee69cc"
    }
    ],
    success: true,
    error: null
    }